name: intl_translation
version: 0.17.10+1
description: >-
  Contains code to deal with internationalized/localized messages,
  date and number formatting and parsing, bi-directional text, and
  other internationalization issues.

homepage: https://github.com/dart-lang/intl_translation
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^2.0.0
  dart_style: ^2.2.1
  intl: ^0.17.0
  path: ^1.8.0
  petitparser: ^4.0.2
dev_dependencies:
  analyzer: ^3.2.0
  test: ^1.20.1
